### ISSUE TITLE
[Feature request] Notification for campustüte

### ISSUE THREAD

**Issue by ddogfoodd** [v411e/ovgumensabot#2]
Notify users about upcoming campustüte events.

**Comment by v411e** [comment]
This is a great idea!

**Comment by ddogfoodd** [comment]
I haven't found announcements about when they are available on their homepage but it seems they announce them on [facebook](https://www.facebook.com/pg/campustuete/events/)

**Comment by v411e** [comment]
Parsing facebook is a bit too much. However I'd appreciate a PR if you want to implement that :) 

Closing this for now. Can be reopened later if needed.
