### ISSUE TITLE
[Feature request] Send information about HiD

### ISSUE THREAD

**Issue by ddogfoodd** [v411e/ovgumensabot#6]
Ist der Bauch in der Mensa erfolgreich gefüllt worden, setzt bei Zeiten Schwerfälligkeit ein. Eines Tages schlief ich nach dem Speisen ein und träumte von einem wunderbaren Kinoabend bei Hörsaal im Dunkeln (HiD). Als ich erwachte, fragte ich mich, ob ein solch wunderbarer Kinoabend nicht Realität werden könne...

Leider schickt der Mensabot die Informationen zu den anstehenden HiD Filmen nicht in die Gruppe...
Schmutz!
Bitte um Behebung, dann gerne wieder 5 Sterne.
Solange das nicht geht: schade dass, man nicht 0 Sterne geben kann.

**Comment by v411e** [comment]
Glücklicherweise ist das Programm von HiD tatsächlich [online verfügbar](https://www.unifilm.de/studentenkinos/MD_HiD) - und das sogar in einem gut zu parsenden Format. Ich freue mich über deinen PR mit einer entsprechenden parser-function, die ein iterable object mit dem aktuellen Programm zurückgibt. Die Integration in das Bot-Interface kann ich gerne übernehmen :)

**Comment by v411e** [comment]
Soll der Bot das regelmäßig von selbst rein schicken oder reicht auch nur auf request?

**Comment by ddogfoodd** [comment]
Request würde ich sagen.
